[development]
DEBUG = true
PORT = 5000
SERVER = "localhost"
MYSQL_DATABASE = "KindnessMap"
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USE_TLS = 1
UPLOADED_IMAGES_URL = "http://localhost:5000/static/photos/"
UPLOADED_IMAGES_DEST = "static/photos"

[testing]

[production]