"""new fields in user

Revision ID: 026a1f537087
Revises: 4130835d2a6b
Create Date: 2018-05-27 22:16:37.487287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026a1f537087'
down_revision = '4130835d2a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('count_logins', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('last_acess', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('registration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'registration_date')
    op.drop_column('User', 'last_acess')
    op.drop_column('User', 'count_logins')
    # ### end Alembic commands ###
