"""new field in kindness model

Revision ID: 0323cd92d08d
Revises: 356a03de6ad0
Create Date: 2018-08-01 23:37:18.280048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0323cd92d08d'
down_revision = '356a03de6ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness', sa.Column('identifier', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'Kindness', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Kindness', type_='unique')
    op.drop_column('Kindness', 'identifier')
    # ### end Alembic commands ###
