"""alter users model

Revision ID: 10e226d4e352
Revises: a14408e7601e
Create Date: 2018-07-08 20:05:59.274719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10e226d4e352'
down_revision = 'a14408e7601e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Users', 'date_birth',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Users', 'genre',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'genre',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('Users', 'date_birth',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Users', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
