"""empty message

Revision ID: 132ee6d8249b
Revises: ad0501450011
Create Date: 2019-01-10 23:23:48.549601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132ee6d8249b'
down_revision = 'ad0501450011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness_Files', sa.Column('size', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kindness_Files', 'size')
    # ### end Alembic commands ###
