"""add file_size column and drop column size

Revision ID: 2920eeb413b3
Revises: 132ee6d8249b
Create Date: 2019-01-10 23:25:05.268627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2920eeb413b3'
down_revision = '132ee6d8249b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kindness_Files', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness_Files', sa.Column('size', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
