"""alter in tags models

Revision ID: 2d46be48e555
Revises: 6b235e516389
Create Date: 2018-07-19 14:26:05.681955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d46be48e555'
down_revision = '6b235e516389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('file_name_marker', sa.String(length=30), nullable=False))
    op.add_column('Tags', sa.Column('path_file_marker', sa.String(length=100), nullable=False))
    op.drop_index('marker', table_name='Tags')
    op.create_unique_constraint(None, 'Tags', ['file_name_marker'])
    op.create_unique_constraint(None, 'Tags', ['path_file_marker'])
    op.drop_column('Tags', 'marker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('marker', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'Tags', type_='unique')
    op.drop_constraint(None, 'Tags', type_='unique')
    op.create_index('marker', 'Tags', ['marker'], unique=True)
    op.drop_column('Tags', 'path_file_marker')
    op.drop_column('Tags', 'file_name_marker')
    # ### end Alembic commands ###
