"""update in field

Revision ID: 356a03de6ad0
Revises: c7a6e9d8bffc
Create Date: 2018-07-24 00:26:58.929005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '356a03de6ad0'
down_revision = 'c7a6e9d8bffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_access', sa.DateTime(), nullable=True))
    op.drop_column('Users', 'last_acess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_acess', mysql.DATETIME(), nullable=True))
    op.drop_column('Users', 'last_access')
    # ### end Alembic commands ###
