"""add field confirmed in users model

Revision ID: 37c8a3274603
Revises: 727fd4d7a586
Create Date: 2018-07-09 22:21:58.230375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37c8a3274603'
down_revision = '727fd4d7a586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kindness', 'confirmed')
    op.add_column('Users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'confirmed')
    op.add_column('Kindness', sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
