"""tags table add

Revision ID: 4130835d2a6b
Revises: ff31ce744698
Create Date: 2018-05-03 22:39:30.884706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4130835d2a6b'
down_revision = 'ff31ce744698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('marker', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('marker')
    )
    op.add_column('Post', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Post', 'Tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Post', type_='foreignkey')
    op.drop_column('Post', 'tag_id')
    op.drop_table('Tags')
    # ### end Alembic commands ###
