"""add tables

Revision ID: 4bd26326b8c5
Revises: 
Create Date: 2018-06-17 20:06:34.911598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd26326b8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('marker', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('marker')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=130), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('last_acess', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('count_logins', sa.Integer(), nullable=True),
    sa.Column('device_ip_register', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Kindness',
    sa.Column('id_kindness', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['Tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id_kindness')
    )
    op.create_table('Tokens_Reset_Password',
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Kindness_Files',
    sa.Column('id_kindness_file', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=6), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('id_kindness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kindness'], ['Kindness.id_kindness'], ),
    sa.PrimaryKeyConstraint('id_kindness_file')
    )
    op.create_table('Likes',
    sa.Column('id_like', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_kindness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kindness'], ['Kindness.id_kindness'], ),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Likes')
    op.drop_table('Kindness_Files')
    op.drop_table('Tokens_Reset_Password')
    op.drop_table('Kindness')
    op.drop_table('Users')
    op.drop_table('Tags')
    # ### end Alembic commands ###
