"""Updated model user

Revision ID: 63f5a8dd56e1
Revises: fb2e64467340
Create Date: 2019-11-27 22:18:46.163976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63f5a8dd56e1'
down_revision = 'fb2e64467340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'auth_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('auth_token', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
