"""alter kindness model

Revision ID: 6b235e516389
Revises: 37c8a3274603
Create Date: 2018-07-17 22:02:06.439086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b235e516389'
down_revision = '37c8a3274603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Kindness', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('Kindness', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('Kindness', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('Kindness', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Kindness', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Kindness', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('Kindness', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('Kindness', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
