"""empty message

Revision ID: 7071662e1d4c
Revises: 7aa83c2f2ead
Create Date: 2019-01-10 21:23:46.822498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7071662e1d4c'
down_revision = '7aa83c2f2ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'status')
    # ### end Alembic commands ###
