"""field confirmed add in users model

Revision ID: 727fd4d7a586
Revises: 10e226d4e352
Create Date: 2018-07-09 22:19:34.762874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727fd4d7a586'
down_revision = '10e226d4e352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kindness', 'confirmed')
    # ### end Alembic commands ###
