"""new fields add

Revision ID: 79d176e0a7b1
Revises: eab0dbafd48d
Create Date: 2018-07-05 22:05:38.374056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d176e0a7b1'
down_revision = 'eab0dbafd48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_birth', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('genre', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'genre')
    op.drop_column('Users', 'date_birth')
    # ### end Alembic commands ###
