"""Add field amount posts in model user

Revision ID: 7f665b980bc3
Revises: cdc976985187
Create Date: 2019-11-28 14:36:23.275664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f665b980bc3'
down_revision = 'cdc976985187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('amount_posts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'amount_posts')
    # ### end Alembic commands ###
