"""Alter table Kindness_Files

Revision ID: 8e6bc008d259
Revises: 42ce830753b5
Create Date: 2018-09-04 09:08:14.016727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e6bc008d259'
down_revision = '42ce830753b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Kindness_Files', 'file_size',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Kindness_Files', 'file_size',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
