"""new field add in kindness

Revision ID: 9fda6710085c
Revises: 79d176e0a7b1
Create Date: 2018-07-08 16:43:01.258785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fda6710085c'
down_revision = '79d176e0a7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness', sa.Column('unnamed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kindness', 'unnamed')
    # ### end Alembic commands ###
