"""add column date_last_login_failed in Users

Revision ID: ad0501450011
Revises: 68c6d4e55ed2
Create Date: 2019-01-10 21:35:37.496181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0501450011'
down_revision = '68c6d4e55ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_last_login_failed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'date_last_login_failed')
    # ### end Alembic commands ###
