"""Add field in model user

Revision ID: cdc976985187
Revises: 63f5a8dd56e1
Create Date: 2019-11-27 22:19:53.028597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc976985187'
down_revision = '63f5a8dd56e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('auth_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'auth_token')
    # ### end Alembic commands ###
