"""field last change add in users

Revision ID: db4e3b8eb160
Revises: 2d46be48e555
Create Date: 2018-07-21 16:29:06.134585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4e3b8eb160'
down_revision = '2d46be48e555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_last_change_pass', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'date_last_change_pass')
    # ### end Alembic commands ###
