"""table add

Revision ID: eab0dbafd48d
Revises: 4bd26326b8c5
Create Date: 2018-06-20 20:36:39.325665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab0dbafd48d'
down_revision = '4bd26326b8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kindness_Tags',
    sa.Column('id_kindness', sa.Integer(), nullable=True),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kindness'], ['Kindness.id_kindness'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['Tags.id'], )
    )
    op.drop_constraint('Kindness_ibfk_1', 'Kindness', type_='foreignkey')
    op.drop_column('Kindness', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kindness', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('Kindness_ibfk_1', 'Kindness', 'Tags', ['tag_id'], ['id'])
    op.drop_table('Kindness_Tags')
    # ### end Alembic commands ###
