"""new fields in tokens table

Revision ID: f600cb6ad8f4
Revises: 0323cd92d08d
Create Date: 2018-08-19 23:07:01.411898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f600cb6ad8f4'
down_revision = '0323cd92d08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tokens',
    sa.Column('id_token', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=True),
    sa.Column('type_token', sa.String(length=15), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token')
    )
    op.drop_index('token', table_name='Tokens_Reset_Password')
    op.drop_table('Tokens_Reset_Password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tokens_Reset_Password',
    sa.Column('id_token', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('send_date', mysql.DATETIME(), nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('was_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id'], name='Tokens_Reset_Password_ibfk_1'),
    sa.PrimaryKeyConstraint('id_token'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'Tokens_Reset_Password', ['token'], unique=True)
    op.drop_table('Tokens')
    # ### end Alembic commands ###
