"""alter users table

Revision ID: fb2e64467340
Revises: 4350713b52f9
Create Date: 2019-11-26 20:30:42.746109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb2e64467340'
down_revision = '4350713b52f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('auth_token', sa.String(length=100), nullable=True))
    op.drop_column('Users', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('Users', 'auth_token')
    # ### end Alembic commands ###
