"""new fields in user table

Revision ID: ff31ce744698
Revises: 47898f814722
Create Date: 2018-04-30 22:20:20.592957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff31ce744698'
down_revision = '47898f814722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('about_me', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'about_me')
    # ### end Alembic commands ###
